FROM nginxinc/nginx-unprivileged
COPY ./index.html /usr/share/nginx/html/index.html

#git commit -m "6.2_html_deploy"
#git push
#docker build -f 6.2_html_deploy/Dockerfile.web6.2 -t ghcr.io/fababum/modul-210:latest 6.2_html_deploy
#docker run -d -p 8080:80 --name module210 ghcr.io/fababum/module-210:v1
#docker stop module210
#docker rm module210
#docker rmi ghcr.io/fababum/module-210:v1
