kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-generic-webhook-secret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  WebHookSecretKey: MWZlZWZkZTMtZGIwZC00N2RjLTljMWUtYzc0NDFjMzRmZDM4
type: Opaque

# es muss 64 String sein mit dem [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("1feefde3-db0d-47dc-9c1e-c7441c34fd38")) kann man es converten